name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - 'noxfile.py'
      - '.github/workflows/deploy.yml'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
      - run: uv run nox -s build-docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Commit updated docs back to the repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'bot: automatic update'
          # https://github.com/actions/checkout/discussions/479
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
